# Generated by Django 3.2 on 2021-04-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
    ]
